### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by Roses4664** [Brian-Wuest/MC-Prefab-Fabric#52] opened 2021-12-05 22:16 UTC
### Minecraft Version

1.18

### Fabric Version

forge version

### Mod Version

forge1.18 - 38.0.15

### Details

Can you please update the forge version of prefab to 1.18 and make it compatible with the latest version of forge?  please please please??

**Comment by Brian-Wuest** [comment] 2021-12-05 22:19
Duplicate of #51.

**Closed as completed by Brian-Wuest** 2021-12-05 22:19 UTC
Labels: enhancement
